# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Packer_Build

steps:
- script: if [ -d "$(output_directory)/gentoo" ]; then rm -rf $(output_directory)/gentoo; fi

  displayName: 'Clear output directory'

- script: |
    ./build-vmware-base.sh $(output_directory)
    echo See https://aka.ms/yaml
  displayName: 'Run Packer build'
  timeoutInMinutes: 0

schedules:
- cron: "0 7 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true
