
trigger:
  branches:
    include:
    - develop
    exclude:
    - master
    - releases/*

pool: Packer_Build

steps:
- checkout: self
  clean: true

- script: if [ -d "$(output_directory)/gentoo" ]; then rm -rf $(output_directory)/gentoo; fi

  displayName: 'Clear output directory'

- script: |
    ./build-vmware-base.sh $(output_directory)
    echo See https://aka.ms/yaml
  displayName: 'Run Packer build'
  timeoutInMinutes: 2880

schedules:
- cron: "0 7 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true
